import express from 'express';
import sharp from 'sharp';
import dotenv from 'dotenv';
import { getAI } from './api/_ai.js';

dotenv.config();

const app = express();
app.use(express.json({ limit: '10mb' }));

async function generateBackground(style: string): Promise<Buffer> {
  const ai = getAI();
  const prompt = `A high-quality artistic background for a QR code, style: ${style}.
Inspired by the beauty of Tahiti and French Polynesia — turquoise lagoons, tropical flowers, Polynesian patterns, lush vegetation.
The image must have a clean, uncluttered CENTER area (about 60% of the image) with soft colors or subtle textures — this is where the QR code will be placed.
The artistic elements (hibiscus flowers, Polynesian motifs, waves) should be concentrated around the EDGES and CORNERS.
High contrast between light areas and decorative elements. No text, no letters, no watermarks.`;

  const negativePrompt = 'text, words, letters, watermark, logo, dark center, busy center, cluttered, people, faces';

  const r = await ai.models.generateImages({
    model: 'imagen-4.0-generate-001',
    prompt,
    config: { numberOfImages: 1, aspectRatio: '1:1', negativePrompt },
  });

  const imageBytes = r.generatedImages?.[0]?.image?.imageBytes;
  if (!imageBytes) throw new Error('No image generated by Imagen');

  const base64 = typeof imageBytes === 'string'
    ? imageBytes
    : Buffer.from(imageBytes).toString('base64');

  return Buffer.from(base64, 'base64');
}

app.post('/api/stylize-qr', async (req, res) => {
  const { qrBase64, style } = req.body;
  if (!qrBase64 || !style) return res.status(400).json({ error: 'qrBase64 and style are required' });

  try {
    const backgroundBuffer = await generateBackground(style);
    const bg = await sharp(backgroundBuffer).resize(1024, 1024).toBuffer();
    const qrBuffer = Buffer.from(qrBase64.split(',')[1], 'base64');
    const qr = await sharp(qrBuffer)
      .resize(800, 800)
      .flatten({ background: { r: 255, g: 255, b: 255 } })
      .toBuffer();

    const result = await sharp(bg)
      .composite([{ input: qr, blend: 'multiply', gravity: 'center' }])
      .png()
      .toBuffer();

    return res.json({ image: `data:image/png;base64,${result.toString('base64')}` });
  } catch (err: any) {
    console.error('Error:', err);
    return res.status(500).json({ error: err.message || 'Failed to stylize QR code' });
  }
});

app.post('/api/generate-background', async (req, res) => {
  const { style, description } = req.body;
  if (!style) return res.status(400).json({ error: 'style is required' });

  try {
    const ai = getAI();
    const prompt = `A high-quality, artistic and elegant background image for a QR code.
Style: ${style}.
${description ? `Description: ${description}.` : ''}
Inspired by the beauty of Tahiti and French Polynesia.
The image should be visually stunning with a clean central area to allow a QR code to be placed on top.
No text, no watermarks.`;

    const negativePrompt = 'text, words, letters, watermark, logo, people, faces, dark center, busy center';

    const r = await ai.models.generateImages({
      model: 'imagen-4.0-generate-001',
      prompt,
      config: { numberOfImages: 1, aspectRatio: '1:1', negativePrompt },
    });

    const imageBytes = r.generatedImages?.[0]?.image?.imageBytes;
    if (!imageBytes) throw new Error('No image generated');

    const base64 = typeof imageBytes === 'string'
      ? imageBytes
      : Buffer.from(imageBytes).toString('base64');

    return res.json({ image: `data:image/png;base64,${base64}` });
  } catch (err: any) {
    console.error('Imagen error:', err);
    return res.status(500).json({ error: err.message || 'Failed to generate background' });
  }
});

const PORT = process.env.SERVER_PORT || 3001;
app.listen(PORT, () => console.log(`Dev API server running on http://localhost:${PORT}`));
