import sharp from 'sharp';
import type { GoogleGenAI } from '@google/genai';

// Overridable via the IMAGEN_MODEL env var (no code change needed to switch models).
// Imagen 3 (imagen-3.0-generate-002) is the most broadly available on Vertex;
// bump to imagen-4.0-generate-001 once the project has access to it.
const IMAGE_MODEL = process.env.IMAGEN_MODEL || 'imagen-3.0-generate-002';

const backgroundPrompt = (style: string) => `A high-quality artistic background for a QR code, style: ${style}.
Inspired by the beauty of Tahiti and French Polynesia — turquoise lagoons, tropical flowers, Polynesian patterns, lush vegetation.
The image must have a clean, uncluttered CENTER area (about 60% of the image) with soft colors or subtle textures — this is where the QR code will be placed.
The artistic elements (hibiscus flowers, Polynesian motifs, waves) should be concentrated around the EDGES and CORNERS.
High contrast between light areas and decorative elements. No text, no letters, no watermarks.`;

const NEGATIVE_PROMPT =
  'text, words, letters, watermark, logo, dark center, busy center, cluttered, people, faces';

/** Generate an artistic Tahiti-themed background image with Imagen. */
export async function generateBackground(ai: GoogleGenAI, style: string): Promise<Buffer> {
  const r = await ai.models.generateImages({
    model: IMAGE_MODEL,
    prompt: backgroundPrompt(style),
    config: { numberOfImages: 1, aspectRatio: '1:1', negativePrompt: NEGATIVE_PROMPT },
  });

  const imageBytes = r.generatedImages?.[0]?.image?.imageBytes;
  if (!imageBytes) throw new Error('No image generated by Imagen');

  const base64 = typeof imageBytes === 'string'
    ? imageBytes
    : Buffer.from(imageBytes).toString('base64');

  return Buffer.from(base64, 'base64');
}

/**
 * Generate a background and composite the QR code on top of it.
 * The QR (white background, black modules) is blended with `multiply`, so white
 * areas let the artwork show through while the dark modules stay scannable.
 */
export async function stylizeQr(ai: GoogleGenAI, qrBase64: string, style: string): Promise<string> {
  const backgroundBuffer = await generateBackground(ai, style);
  const bg = await sharp(backgroundBuffer).resize(1024, 1024).toBuffer();

  const qrBuffer = Buffer.from(qrBase64.split(',')[1], 'base64');
  const qr = await sharp(qrBuffer)
    .resize(800, 800)
    .flatten({ background: { r: 255, g: 255, b: 255 } })
    .toBuffer();

  const result = await sharp(bg)
    .composite([{ input: qr, blend: 'multiply', gravity: 'center' }])
    .png()
    .toBuffer();

  return `data:image/png;base64,${result.toString('base64')}`;
}
