import type { VercelRequest, VercelResponse } from '@vercel/node';
import { getAI } from './_ai';
import sharp from 'sharp';

async function generateBackground(ai: any, style: string): Promise<Buffer> {
  const prompt = `A high-quality artistic background for a QR code, style: ${style}.
Inspired by the beauty of Tahiti and French Polynesia — turquoise lagoons, tropical flowers, Polynesian patterns, lush vegetation.
The image must have a clean, uncluttered CENTER area (about 60% of the image) with soft colors or subtle textures — this is where the QR code will be placed.
The artistic elements (hibiscus flowers, Polynesian motifs, waves) should be concentrated around the EDGES and CORNERS.
High contrast between light areas and decorative elements. No text, no letters, no watermarks.`;

  const negativePrompt = 'text, words, letters, watermark, logo, dark center, busy center, cluttered, people, faces';

  const r = await ai.models.generateImages({
    model: 'imagen-4.0-generate-001',
    prompt,
    config: {
      numberOfImages: 1,
      aspectRatio: '1:1',
      negativePrompt,
    },
  });

  const imageBytes = r.generatedImages?.[0]?.image?.imageBytes;
  if (!imageBytes) throw new Error('No image generated by Imagen');

  const base64 = typeof imageBytes === 'string'
    ? imageBytes
    : Buffer.from(imageBytes).toString('base64');

  return Buffer.from(base64, 'base64');
}

export default async function handler(req: VercelRequest, res: VercelResponse) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const { qrBase64, style } = req.body as { qrBase64?: string; style?: string };

  if (!qrBase64 || !style) {
    return res.status(400).json({ error: 'qrBase64 and style are required' });
  }

  try {
    const ai = getAI();

    // 1. Generate artistic background with Imagen
    const backgroundBuffer = await generateBackground(ai, style);

    // 2. Resize background to 1024x1024
    const bg = await sharp(backgroundBuffer)
      .resize(1024, 1024)
      .toBuffer();

    // 3. Prepare QR code — resize to 800x800, ensure white background
    const qrBuffer = Buffer.from(qrBase64.split(',')[1], 'base64');
    const qr = await sharp(qrBuffer)
      .resize(800, 800)
      .flatten({ background: { r: 255, g: 255, b: 255 } })
      .toBuffer();

    // 4. Composite: place QR centered on background with multiply blend
    //    multiply: white areas let background show through, black modules stay dark
    const result = await sharp(bg)
      .composite([{
        input: qr,
        blend: 'multiply',
        gravity: 'center',
      }])
      .png()
      .toBuffer();

    return res.json({ image: `data:image/png;base64,${result.toString('base64')}` });
  } catch (err: any) {
    console.error('Error:', err);
    return res.status(500).json({ error: err.message || 'Failed to generate QR code' });
  }
}
